theme = "congo"

# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://robertboscacci.com/"
defaultContentLanguage = "en"
languageCode = "en"

enableRobotsTXT = true
pagination.pagerSize = 10
summaryLength = 2

[outputs]
home = ["HTML", "RSS", "JSON"]
